### ISSUE TITLE
Add feature hidde xposed detected

### ISSUE THREAD

**Issue by QPLAYid** [ALEX5402/xposd-dll-injector-By-alex5402#1]

**Comment by ALEX5402** [comment]
> Please add xposed feature hide detected xposed api

Can you provide a better context about this feature  ?

**Comment by QPLAYid** [comment]
Some game detected xposed dll injector ,maybe detected api xposed dll injector

**Comment by QPLAYid** [comment]
> > Please add xposed feature hide detected xposed api
> 
> Can you provide a better context about this feature ?

https://github.com/Katana-Official/XYNXposed
